### ISSUE TITLE
Detail page for the task

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#241] opened 2016-11-13 16:29 UTC
The task detail page should have
- Edit option of the task
- Task discussion section of the task
- Discussion part should allow markdown, nudge, emoji
- Nudge should send email to the mentioned user
- Mentioned users list should be assigned to and all users associated to the project
- Should have close option
- Each discussion should have option to add hours worked.

Sub-task of https://github.com/sQcrm/sqcrm/issues/234

**Comment by abhikchakraborty** [comment] 2017-01-22 07:54
Closing this duplicate of https://github.com/sQcrm/sqcrm/issues/239

**Closed by abhikchakraborty** 2017-01-22 07:54 UTC
Labels: coding, feature
